version: '3.8'

services:
  weather-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Enable hot reload
      - .:/usr/src/app
      # Prevent overwriting node_modules
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    env_file:
      - .env.development
    networks:
      - weather-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  weather-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - weather-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  weather-network:
    driver: bridge

volumes:
  node_modules: